config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  # get 'questions/index'
  # get 'questions/show'
  # get 'questions/new'
  # get 'questions/edit'
  
  root 'questions#index'
  
  resources :questions do
    resources :answers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :name, presence: true
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
    
    validates :name, presence: true
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    if @answer.update(answer_params)
      
      redirect_to question_path(@question), notice: '回答投稿完了'
      
    else
      
      redirect_to question_path(@question), alert: '回答失敗'
      # render question_path
      # flash[:alert] = '回答失敗'
      
    end
  end
  
  def edit
    # @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end
  
  def update
    # @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    
    if @answer.update(answer_params)
      
      redirect_to question_path(@question), notice: '回答編集完了'
      
    else
      flash[:alert] = '回答編集失敗'
      render :edit
    end
  end
  
  def destroy
    # @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    
    @answer.destroy
    redirect_to question_path(@question), notice: '削除完了'
      
  end
  
  private
  
  def set_question
    @question = Question.find(params[:question_id])
  end

   def answer_params
     params.require(:answer).permit(:content, :name, :question_id)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    
    if @question.save
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = 'Save error!'
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    
    if @question.update(question_params)
      redirect_to root_path, notice: 'Update Complete!'
    else
      flash.now[:alert] = 'Update error!'
      render :edit
    end
  end
  
  def destroy
    
    @question = Question.find(params[:id])
    
    @question.destroy
    
    redirect_to root_path, notice: 'Delete Complete!'
  end
  
  private
    # ストロングパラメータのためのメソッド
    def question_params
      # byebug
      params.require(:question).permit(:name, :title, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/edit.html.erb
<div>
  <h2>回答更新画面</h2>
  <%= form_with model:[@question, @answer], local: true do |f| %>
    <div class="form_group">
      <div class="form_group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      
      <div class="form_group">
        <label>Content</label>
        <%= f.text_field :content, class: "form-control"%>
      </div>
      
      <div class="text-center">
        <%= f.submit "更新", class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <P class="text-success"><%= flash[:notice] %></P>
      <% end %>
      
      <% if flash[:alert] %>
        <P class="text-danger"><%= flash[:alert] %></P>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |f| %>
  <div class="form_group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form_group">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form_group">
    <label>Content</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <input tyoe="button" value='戻る' onClick="location.href='/'" class="btn btn-primary">
  </div>
<% end %>

app/views/questions/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">Edit Question</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/questions/index.html.erb
<h2>Questions</h2>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped"
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Menu</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question| %>
          <tr>
            <td><%= question.id %></td>
            <td><%= link_to question.title, question_path(question) %></td>
            <td>[<%= link_to '編集', edit_question_path(question) %>]
            [<%= link_to '削除', question_path(question), method: :delete, data: { confirm: '削除してよろしいですか？' } %>]</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= link_to '新規質問画面', new_question_path %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">New Question</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @question.title %></h1>
    <div>
      Content: <%= @question.content %>
    </div>
    <div>
      Name: <%= @question.name %>
    </div>
    <hr>
    
    <div>
      <h3>回答</h3>
      <table class="table table-striped">
      <% if @question.answers.any? %>
        <thead class="thead-light">
          <tr>
            <td>Answer</td>
            <td>Name</td>
            <td>Menu</td>
          </tr>
        </thead>
        <tbody>
          <%@question.answers.each do |answer| %>
            <tr>
              <td>
                <%= answer.content %>
              </td>
              <td>
                <%= answer.name %>
              </td>
              <td>
                [ <%= link_to '編集', edit_question_answer_path(@question, answer) %> ] 
                [ <%= link_to '削除', question_answer_path(@question, answer), method: :delete, data: {confirm: '削除してよろしいですか？'} %> ]
              </td>
            </tr>
          <% end %>
        </tbody>
      <% else %>
        <P>回答がありません。</P>
      <% end %>
      </table>
    </div>
    
    <h3>回答一覧</h3>
    <%= form_with model: [@question, @answer], local: true do |f| %>
      <%= f.hidden_field :question_id, { value: @question.id } %>
      <div class="form_group">
        <label>Name</label>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      
      <div class="form_group">
        <label>Content</label>
        <%= f.text_area :content, class: 'form-control'%>
      </div>
      <div class="text-center">
        <%= f.submit "投稿", class: 'btb btn-primary' %>
      </div>
    <% end %>
    <div>
      <%= link_to '質問一覧画面', root_path %>
    </div>
  </div>
</div>